src/dashboard/forms/__init__.py
from .company_form import CompanySettingForm
from .owner_form import OwnerSettingForm

__all__ = (
    "CompanySettingForm",
    "OwnerSettingForm",
)

src/dashboard/forms/company_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired, Optional, ValidationError

from src.dashboard.forms.default_form import DefaultForm


class CompanySettingForm(DefaultForm, FlaskForm):
    fullname = StringField(
        label="Nom du gestionnaire",
        render_kw={"required": True},
        validators=[InputRequired()],
    )
    agencie_name = StringField(
        label="Nom de votre agence",
        render_kw={"required": True},
        validators=[InputRequired()],
    )
    location = StringField(label="Situation géographique", validators=[Optional()])
    submit = SubmitField(label="Enregistrer les modifications")

    def validate_fullname(self, fullname):
        excluded_chars = "*?!'^+%&/()=}][{$#"
        for char in self.fullname.data:
            if char in excluded_chars:
                raise ValidationError(f"Character {char} is not allowed in fullname.")

src/dashboard/forms/default_form.py
from wtforms import SelectField, StringField
from wtforms.validators import InputRequired, Optional

from src.constants import DEVISE, DEVISE_DEFAULT, GENDER, GENDER_DEFAULT


class DefaultForm:
    gender = SelectField(
        label="Genre",
        choices=GENDER,
        coerce=str,
        default=GENDER_DEFAULT,
        validators=[Optional()],
    )
    phonenumber_two = StringField(
        label="Numéro de téléphone 2", validators=[Optional()]
    )
    devise = SelectField(
        label="Devise",
        render_kw={"required": True},
        validators=[InputRequired()],
        choices=DEVISE,
        coerce=str,
        default=DEVISE_DEFAULT,
    )

src/dashboard/forms/owner_form.py
from flask_wtf import FlaskForm
from wtforms import DateField, StringField, SubmitField
from wtforms.validators import InputRequired, Optional

from src.dashboard.forms.default_form import DefaultForm


class OwnerSettingForm(DefaultForm, FlaskForm):
    fullname = StringField(
        label="Nom & prénom", render_kw={"required": True}, validators=[InputRequired()]
    )
    profession = StringField(label="Votre profession", validators=[Optional()])
    parent_name = StringField("Nom d'un parent", validators=[Optional()])
    location = StringField(label="Lieu de résidence", validators=[Optional()])
    birthdate = DateField(label="Date de naissance", validators=[Optional()])
    submit = SubmitField(label="Enregistrer les modifications")

src/dashboard/routes/__init__.py
from .admin import admin_bp
from .agency import agency_bp
from .checkout import checkout_bp
from .owner import owner_bp

__all__ = ("owner_bp", "agency_bp", "checkout_bp", "admin_bp")

src/dashboard/routes/admin.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required

from src.mixins.decorators import admin_required

admin_bp = Blueprint("admin_bp", __name__, url_prefix="/admin/dashboard/")


@admin_bp.get("/")
@login_required
@admin_required
def dashboard():
    page_title = "Tableau de board"
    return render_template(
        "dashboard/dashboard.html", page_title=page_title, current_user=current_user
    )

src/dashboard/routes/agency.py
from datetime import datetime

from flask import (
    abort,
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    Response,
    session,
    url_for,
)
from flask_login import current_user, login_required, logout_user

from src.auth.models import VNUser
from src.dashboard.forms import CompanySettingForm
from src.dashboard.services import export_data
from src.exts import cache, csrf
from src.mixins.decorators import agency_required

agency_bp = Blueprint("agency_bp", __name__, url_prefix="/dashboard/")
csrf.exempt(agency_bp)


@agency_bp.route("/settings/", methods=["GET", "POST"])
@login_required
@agency_required
def agency_setting():
    page_title = "Paramètres"
    form = CompanySettingForm()

    if request.method == "POST" and form.validate_on_submit():
        current_user.vn_gender = form.gender.data
        current_user.vn_fullname = form.fullname.data
        current_user.vn_phonenumber_two = form.phonenumber_two.data

        current_user.vn_agencie_name = form.agencie_name.data

        current_user.vn_location = form.location.data
        current_user.vn_device = form.devise.data

        current_user.save()
        flash("Votre compte a été mise à jour avec succès.", "success")
        return redirect(url_for("agency_bp.agency_setting"))
    elif request.method == "GET":
        form.gender.data = current_user.vn_gender
        form.fullname.data = current_user.vn_fullname

        form.phonenumber_two.data = current_user.vn_phonenumber_two
        form.agencie_name.data = current_user.vn_agencie_name

        form.location.data = current_user.vn_location
        form.devise.data = current_user.vn_device

    return render_template(
        "dashboard/account/company/settings.html",
        page_title=page_title,
        form=form,
        current_user=current_user,
    )


@agency_bp.get("/tenants/")
@login_required
def agency_create_tenant():
    page_title = "Vos locataires"

    return render_template(
        "tenant/tenant.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.get("/billing/")
@login_required
@agency_required
def agency_billing():
    page_title = "Facturation"

    return render_template(
        "dashboard/account/billing.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.get("/houses/")
@login_required
@cache.cached(timeout=500)
def agency_house_list():
    page_title = "Propriétés"

    return render_template(
        "tenant/house.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.get("/lessors/")
@login_required
@agency_required
@cache.cached(timeout=500)
def agency_owner_list():
    page_title = "Vos bailleurs"

    return render_template(
        "tenant/owner.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.get("/check-houses/")
@login_required
@agency_required
@cache.cached(timeout=500)
def check_houses():
    page_title = "Trouver des propriétés dans votre zone"

    return render_template(
        "dashboard/account/houses.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.route("/delete-account/", methods=["POST"])
@login_required
def delete_account():
    user = VNUser.get_user_logged()
    if current_user != user:
        abort(400)
    try:
        user.disable()
        logout_user()
        session.clear()
        flash("Votre compte a été supprimé avec succès !", category="success")
        return redirect(url_for("auth_bp.login"))
    except Exception as e:
        abort(500, f"Une erreur s'est produite: {e}")


@agency_bp.get("/export-tenants-data/")
@login_required
def export_tenants_csv():
    headers = [
        "ID",
        "Nom & Prénoms",
        "N° Téléphone",
        "Adresse e-mail",
        "N° CNI",
        "Profession",
        "Loyer",
        "Date d'ajout",
    ]

    tenants = current_user.tenants.all()

    current_date = datetime.now().strftime("%Y-%m-%d_%H-%M")
    response = Response(
        export_data.generate_tenant_csv(tenants, headers), mimetype="text/csv"
    )

    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="tenants_data{}.csv".format(current_date),
    )
    return response


@agency_bp.get("/export-owners-data/")
@login_required
def export_owners_csv():
    headers = [
        "ID",
        "Nom & Prénoms",
        "N° Téléphone",
        "Adresse e-mail",
        "N° CNI",
        "Profession",
        "Nombre de propriétés",
        "Date d'ajout",
    ]

    owners = current_user.houseowners.all()

    current_date = datetime.now().strftime("%Y-%m-%d_%H-%M")
    response = Response(
        export_data.generate_owner_csv(owners, headers), mimetype="text/csv"
    )

    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="owners_data_{}.csv".format(current_date),
    )
    return response


@agency_bp.get("/export-houses-data/")
@login_required
def export_houses_csv():
    headers = [
        "ID",
        "Propriétaire",
        "Type de propriété",
        "Loyer",
        "Caution",
        "Nombre de pièces",
        "Situation géographique",
        "Date de mise en location",
        "Disponibilité de la propriété",
        "Date d'ajout",
    ]

    houses = current_user.houses.all()

    current_date = datetime.now().strftime("%Y-%m-%d_%H-%M")
    response = Response(
        export_data.generate_house_csv(houses, headers), mimetype="text/csv"
    )

    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="houses_data_{}.csv".format(current_date),
    )
    return response


@agency_bp.get("/export-payments-data/")
@login_required
def export_payments_csv():
    headers = [
        "ID Transaction",
        "ID Opérateur",
        "Nom & prénom du locataire",
        "Loyer (montant)",
        "Méthode de paiement",
        "Date de paiement",
    ]

    payments = current_user.payments.all()

    current_date = datetime.now().strftime("%Y-%m-%d_%H-%M")
    response = Response(
        export_data.generate_payments_csv(payments, headers), mimetype="text/csv"
    )

    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="payments_data_{}.csv".format(current_date),
    )
    return response

src/dashboard/routes/checkout.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required

checkout_bp = Blueprint("checkout_bp", __name__, url_prefix="/dashboard/")


@checkout_bp.get("/payments/")
@login_required
def checkout():
    page_title = "Liste des paiements de loyers"
    return render_template(
        "checkout/checkout.html", page_title=page_title, current_user=current_user
    )


@checkout_bp.get("/requests/")
@login_required
def transfer_request():
    page_title = "Retraits"
    return render_template(
        "checkout/transfer.html", page_title=page_title, current_user=current_user
    )

src/dashboard/routes/owner.py
import os

from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from flask_login import current_user, login_required

from src.auth.forms.auth_form import ChangePasswordForm
from src.dashboard.forms import OwnerSettingForm
from src.exts import cache, csrf
from src.mixins.decorators import owner_required

owner_bp = Blueprint("owner_bp", __name__, url_prefix="/dashboard/")
csrf.exempt(owner_bp)


@owner_bp.route("/index/", methods=["GET"])
@login_required
@cache.cached(timeout=500)
def dashboard():
    page_title = "Tableau de board"
    return render_template(
        "dashboard/dashboard.html", page_title=page_title, current_user=current_user
    )


@owner_bp.route("/parameters/", methods=["GET", "POST"])
@login_required
@owner_required
def owner_setting():
    page_title = "Paramètres"
    form = OwnerSettingForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        current_user.vn_gender = form.gender.data
        current_user.vn_fullname = form.fullname.data
        current_user.vn_phonenumber_two = form.phonenumber_two.data

        current_user.vn_profession = form.profession.data
        current_user.vn_parent_name = form.parent_name.data

        current_user.vn_device = form.devise.data
        current_user.vn_location = form.location.data
        current_user.vn_birthdate = form.birthdate.data

        current_user.save()
        flash("Votre compte a été mise à jour avec succès.", "success")
        return redirect(url_for("owner_bp.owner_setting"))
    elif request.method == "GET":
        form.gender.data = current_user.vn_gender
        form.fullname.data = current_user.vn_fullname
        form.phonenumber_two.data = current_user.vn_phonenumber_two

        form.profession.data = current_user.vn_profession
        form.parent_name.data = current_user.vn_parent_name

        form.devise.data = current_user.vn_device
        form.location.data = current_user.vn_location
        form.birthdate.data = current_user.vn_birthdate

    return render_template(
        "dashboard/account/owner/settings.html",
        page_title=page_title,
        form=form,
        current_user=current_user,
    )


@owner_bp.route("/change-paswword/", methods=["GET", "POST"])
@login_required
def change_password():
    page_title = "Changer votre mot de passe"
    form = ChangePasswordForm()
    if request.method == "POST" and form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.vn_password = form.new_password.data
            current_user.set_password(form.new_password.data)
            current_user.save()
            flash("Votre mot de passe a été mise à jour avec succès.", "success")
            return redirect(url_for("owner_bp.change_password"))
        else:
            flash("Le mot de passe est invalide.", category="danger")

    return render_template(
        "dashboard/account/password.html",
        page_title=page_title,
        form=form,
        current_user=current_user,
    )


@owner_bp.route("/<filename>/")
@cache.cached(timeout=500)
def avatar(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER_PATH"], filename)


@owner_bp.route("/favicon.png")
@cache.cached(timeout=500)
def favicon():
    return send_from_directory(
        os.path.join(current_app.root_path, "static"), "img/logo/favicon.png"
    )

src/templates/dashboard/partials/_layoutsidenav.html
<div id="layoutSidenav_nav">
    <nav class="sidenav shadow-right sidenav-light">
        <div class="sidenav-menu">
            <div class="nav accordion" id="accordionSidenav">
                <div class="sidenav-menu-heading d-sm-none">
                    Mon Compte
                </div>

                {# <a class="nav-link d-sm-none" href="#!">
                    <div class="nav-link-icon">
                        <i data-feather="bell"></i>
                    </div>
                    Alertes
                    <span class="badge bg-warning-soft text-warning ms-auto">4 New!</span>
                </a>
                <a class="nav-link d-sm-none" href="#!">
                    <div class="nav-link-icon">
                        <i data-feather="mail"></i>
                    </div>
                    Messages
                    <span class="badge bg-success-soft text-success ms-auto">2 New!</span>
                </a>  #}

                <div class="sidenav-menu-heading">Menu Venone</div>

                <a class="nav-link" href="{{ url_for('owner_bp.dashboard') }}">
                    <div class="nav-link-icon">
                        <i data-feather="home"></i>
                    </div> Tableau de board
                </a>

                <div class="sidenav-menu-heading">Gestion Loyers</div>
                <a class="nav-link" href="{{ url_for('checkout_bp.checkout') }}">
                    <div class="nav-link-icon">
                        <i data-feather="dollar-sign"></i>
                    </div> Paiements (Loyers)
                </a>
                <a class="nav-link" href="{{ url_for('checkout_bp.transfer_request') }}">
                    <div class="nav-link-icon">
                        <i data-feather="dollar-sign"></i>
                    </div> Retraits
                </a>

                {% if current_user.vn_company %}
                    <div class="sidenav-menu-heading">Gestion locataires</div>
                    <a class="nav-link" href="{{ url_for("agency_bp.agency_create_tenant") }}">
                        <div class="nav-link-icon">
                            <i data-feather="users"></i>
                        </div>
                        Locataires
                    </a>

                    {# <a class="nav-link" href="#!">
                        <div class="nav-link-icon">
                            <i data-feather="grid"></i>
                        </div> Arriérés
                    </a> #}

                    <div class="sidenav-menu-heading">Gestion Bailleurs</div>
                    <a class="nav-link" href="{{ url_for("agency_bp.agency_owner_list") }}">
                        <div class="nav-link-icon">
                            <i data-feather="users"></i>
                        </div>
                        Bailleurs
                    </a>
                {% endif %}

                {% if current_user.vn_house_owner %}
                    <div class="sidenav-menu-heading">Gestion locataires</div>
                    <a class="nav-link" href="{{ url_for("agency_bp.agency_create_tenant") }}">
                        <div class="nav-link-icon">
                            <i data-feather="users"></i>
                        </div>
                        Locataires
                    </a>
                {% endif %}

                <div class="sidenav-menu-heading">Gestion Propriétés</div>
                <a class="nav-link" href="{{ url_for('agency_bp.agency_house_list') }}">
                    <div class="nav-link-icon">
                        <i data-feather="home"></i>
                    </div> Propriétés
                </a>

                {% if current_user.vn_company %}
                    <a class="nav-link" href="{{ url_for('agency_bp.check_houses') }}">
                        <div class="nav-link-icon">
                            <i data-feather="home"></i>
                        </div> Autres propriétés
                    </a>

                    {# <div class="sidenav-menu-heading">Rapports</div>
                    <a class="nav-link" href="#!">
                        <div class="nav-link-icon">
                            <i data-feather="bar-chart"></i>
                        </div>
                        Rapports
                    </a>
                    <a class="nav-link" href="#!">
                        <div class="nav-link-icon">
                            <i data-feather="bell"></i>
                        </div>
                        Notifications
                    </a> #}

                {% endif %}

                <div class="sidenav-menu-heading">paramètres</div>

                {% if current_user.vn_house_owner %}
                    <a class="nav-link" href="{{ url_for("owner_bp.owner_setting") }}">
                        <div class="nav-link-icon">
                            <i data-feather="settings"></i>
                        </div>
                        Paramètre du compte
                    </a>
                {% elif current_user.vn_company %}
                    <a class="nav-link" href="{{ url_for("agency_bp.agency_billing") }}">
                        <div class="nav-link-icon">
                            <i data-feather="credit-card"></i>
                        </div>
                        Facturation
                    </a>

                    <a class="nav-link" href="{{ url_for("agency_bp.agency_setting") }}">
                        <div class="nav-link-icon">
                            <i data-feather="settings"></i>
                        </div>
                        Paramètre du compte
                    </a>
                {% endif %}
            </div>
        </div>

        <!-- Sidenav Footer-->
        <div class="sidenav-footer">
            <div class="sidenav-footer-content">
                <div class="sidenav-footer-subtitle">
                Connecté en tant que:</div>
                <div class="sidenav-footer-title">
                    {{ current_user.get_name() }}
                </div>
            </div>
        </div>
    </nav>
</div>

src/templates/dashboard/partials/_sidenav.html
{% set avatar = url_for('static', filename="img/element/avatar.png") %}

<nav class="topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white" id="sidenavAccordion">

    <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 me-2 ms-lg-2 me-lg-0 shadow-none" id="sidebarToggle">
        <i data-feather="menu"></i>
    </button>

    <a class="navbar-brand pe-3 ps-4 ps-lg-2" href="{{ url_for('owner_bp.dashboard') }}">
        {{ current_user.get_name() }}
    </a>

    <ul class="navbar-nav align-items-center ms-auto">

        {# <li class="nav-item dropdown no-caret d-none d-sm-block me-3 dropdown-notifications">
            <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownAlerts" href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="bell"></i></a>
            <div class="dropdown-menu dropdown-menu-end border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownAlerts">
                <h6 class="dropdown-header dropdown-notifications-header">
                    <i class="me-2" data-feather="bell"></i>
                    Alerte Center
                </h6>

                <a class="dropdown-item dropdown-notifications-item" href="#!">
                    <div class="dropdown-notifications-item-icon bg-warning"><i data-feather="activity"></i></div>
                    <div class="dropdown-notifications-item-content">
                        <div class="dropdown-notifications-item-content-details">December 29, 2021</div>
                        <div class="dropdown-notifications-item-content-text">This is an alert message. It's nothing serious, but it requires your attention.</div>
                    </div>
                </a>
                <a class="dropdown-item dropdown-notifications-footer" href="#!">View All Alerts</a>
            </div>
        </li>

        <li class="nav-item dropdown no-caret d-none d-sm-block me-3 dropdown-notifications">
            <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownMessages" href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="mail"></i></a>
            <div class="dropdown-menu dropdown-menu-end border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownMessages">
                <h6 class="dropdown-header dropdown-notifications-header">
                    <i class="me-2" data-feather="mail"></i>
                    Messages
                </h6>
                <a class="dropdown-item dropdown-notifications-item" href="#!">
                    <div class="dropdown-notifications-item-content">
                        <div class="dropdown-notifications-item-content-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit,</div>
                        <div class="dropdown-notifications-item-content-details">Thomas Wilcox · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item dropdown-notifications-footer" href="#!">Read All Messages</a>
            </div>
        </li> #}

        <li class="nav-item dropdown no-caret dropdown-user me-3 me-lg-4">
            <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownUserImage" href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img loading="lazy" class="img-fluid" src="{{ avatar }}" loading="lazy"/></a>

            <div class="dropdown-menu dropdown-menu-end border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownUserImage">
                <h6 class="dropdown-header d-flex align-items-center">
                    <img class="dropdown-user-img" src="{{ avatar }}" />
                    <div class="dropdown-user-details">
                        <div class="dropdown-user-details-name">
                            {{ current_user.get_name() }}
                        </div>
                        <div class="dropdown-user-details-email">
                            {{ current_user.vn_addr_email }}
                        </div>
                    </div>
                </h6>

                <div class="dropdown-divider"></div>

                {% if current_user.vn_house_owner %}
                    <a class="dropdown-item" href="{{ url_for("owner_bp.owner_setting") }}">
                        <div class="dropdown-item-icon">
                        <i data-feather="settings"></i></div>
                        Paramètre du compte
                    </a>
                {% endif %}

                {% if current_user.vn_company %}
                    <a class="dropdown-item" href="{{ url_for("agency_bp.agency_setting") }}">
                        <div class="dropdown-item-icon">
                        <i data-feather="settings"></i></div>
                        Paramètre du compte
                    </a>
                {% endif %}

                <a class="dropdown-item" href="#!">
                    <div class="dropdown-item-icon">
                    <i data-feather="help-circle"></i></div>
                    Centre d'aide
                </a>
                <a class="dropdown-item" href="{{  url_for('auth_bp.logout') }}">
                    <div class="dropdown-item-icon">
                        <i data-feather="log-out"></i>
                    </div>
                    Se déconnecter
                </a>
            </div>
        </li>
    </ul>
</nav>