src/dashboard/forms/__init__.py
from .company_form import CompanySettingForm
from .owner_form import OwnerSettingForm

__all__ = (
    "CompanySettingForm",
    "OwnerSettingForm",
)

src/dashboard/forms/company_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired, Optional, ValidationError

from src.dashboard.forms.default_form import DefaultForm


class CompanySettingForm(DefaultForm, FlaskForm):
    fullname = StringField(
        label="Nom du gestionnaire",
        render_kw={"required": True},
        validators=[InputRequired()],
    )
    agencie_name = StringField(
        label="Nom de votre agence",
        render_kw={"required": True},
        validators=[InputRequired()],
    )
    location = StringField(label="Situation géographique", validators=[Optional()])
    submit = SubmitField(label="Enregistrer les modifications")

    def validate_fullname(self, fullname):
        excluded_chars = "*?!'^+%&/()=}][{$#"
        for char in self.fullname.data:
            if char in excluded_chars:
                raise ValidationError(f"Character {char} is not allowed in fullname.")

src/dashboard/forms/default_form.py
from wtforms import SelectField, StringField
from wtforms.validators import InputRequired, Optional

from src.constants import DEVISE, DEVISE_DEFAULT, GENDER, GENDER_DEFAULT


class DefaultForm:
    gender = SelectField(
        label="Genre",
        choices=GENDER,
        coerce=str,
        default=GENDER_DEFAULT,
        validators=[Optional()],
    )
    phonenumber_two = StringField(
        label="Numéro de téléphone 2", validators=[Optional()]
    )
    devise = SelectField(
        label="Devise",
        render_kw={"required": True},
        validators=[InputRequired()],
        choices=DEVISE,
        coerce=str,
        default=DEVISE_DEFAULT,
    )

src/dashboard/forms/owner_form.py
from flask_wtf import FlaskForm
from wtforms import DateField, StringField, SubmitField
from wtforms.validators import InputRequired, Optional

from src.dashboard.forms.default_form import DefaultForm


class OwnerSettingForm(DefaultForm, FlaskForm):
    fullname = StringField(
        label="Nom & prénom", render_kw={"required": True}, validators=[InputRequired()]
    )
    profession = StringField(label="Votre profession", validators=[Optional()])
    parent_name = StringField("Nom d'un parent", validators=[Optional()])
    location = StringField(label="Lieu de résidence", validators=[Optional()])
    birthdate = DateField(label="Date de naissance", validators=[Optional()])
    submit = SubmitField(label="Enregistrer les modifications")

src/dashboard/routes/__init__.py
from .admin import admin_bp
from .agency import agency_bp
from .checkout import checkout_bp
from .owner import owner_bp

__all__ = ("owner_bp", "agency_bp", "checkout_bp", "admin_bp")

src/dashboard/routes/admin.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required

from src.mixins.decorators import admin_required

admin_bp = Blueprint("admin_bp", __name__, url_prefix="/admin/dashboard/")


@admin_bp.get("/")
@login_required
@admin_required
def dashboard():
    page_title = "Tableau de board"
    return render_template(
        "dashboard/dashboard.html", page_title=page_title, current_user=current_user
    )

src/dashboard/routes/agency.py
from datetime import datetime

from flask import (
    abort,
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    Response,
    session,
    url_for,
)
from flask_login import current_user, login_required, logout_user

from src.auth.models import VNUser
from src.dashboard.forms import CompanySettingForm
from src.dashboard.services import export_data
from src.exts import cache, csrf
from src.mixins.decorators import agency_required

agency_bp = Blueprint("agency_bp", __name__, url_prefix="/dashboard/")
csrf.exempt(agency_bp)


@agency_bp.route("/settings/", methods=["GET", "POST"])
@login_required
@agency_required
def agency_setting():
    page_title = "Paramètres"
    form = CompanySettingForm()

    if request.method == "POST" and form.validate_on_submit():
        current_user.vn_gender = form.gender.data
        current_user.vn_fullname = form.fullname.data
        current_user.vn_phonenumber_two = form.phonenumber_two.data

        current_user.vn_agencie_name = form.agencie_name.data

        current_user.vn_location = form.location.data
        current_user.vn_device = form.devise.data

        current_user.save()
        flash("Votre compte a été mise à jour avec succès.", "success")
        return redirect(url_for("agency_bp.agency_setting"))
    elif request.method == "GET":
        form.gender.data = current_user.vn_gender
        form.fullname.data = current_user.vn_fullname

        form.phonenumber_two.data = current_user.vn_phonenumber_two
        form.agencie_name.data = current_user.vn_agencie_name

        form.location.data = current_user.vn_location
        form.devise.data = current_user.vn_device

    return render_template(
        "dashboard/account/company/settings.html",
        page_title=page_title,
        form=form,
        current_user=current_user,
    )


@agency_bp.get("/tenants/")
@login_required
def agency_create_tenant():
    page_title = "Vos locataires"

    return render_template(
        "tenant/tenant.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.get("/billing/")
@login_required
@agency_required
def agency_billing():
    page_title = "Facturation"

    return render_template(
        "dashboard/account/billing.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.get("/houses/")
@login_required
@cache.cached(timeout=500)
def agency_house_list():
    page_title = "Propriétés"

    return render_template(
        "tenant/house.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.get("/lessors/")
@login_required
@agency_required
@cache.cached(timeout=500)
def agency_owner_list():
    page_title = "Vos bailleurs"

    return render_template(
        "tenant/owner.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.get("/check-houses/")
@login_required
@agency_required
@cache.cached(timeout=500)
def check_houses():
    page_title = "Trouver des propriétés dans votre zone"

    return render_template(
        "dashboard/account/houses.html",
        page_title=page_title,
        current_user=current_user,
    )


@agency_bp.route("/delete-account/", methods=["POST"])
@login_required
def delete_account():
    user = VNUser.get_user_logged()
    if current_user != user:
        abort(400)
    try:
        user.disable()
        logout_user()
        session.clear()
        flash("Votre compte a été supprimé avec succès !", category="success")
        return redirect(url_for("auth_bp.login"))
    except Exception as e:
        abort(500, f"Une erreur s'est produite: {e}")


@agency_bp.get("/export-tenants-data/")
@login_required
def export_tenants_csv():
    headers = [
        "ID",
        "Nom & Prénoms",
        "N° Téléphone",
        "Adresse e-mail",
        "N° CNI",
        "Profession",
        "Loyer",
        "Date d'ajout",
    ]

    tenants = current_user.tenants.all()

    current_date = datetime.now().strftime("%Y-%m-%d_%H-%M")
    response = Response(
        export_data.generate_tenant_csv(tenants, headers), mimetype="text/csv"
    )

    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="tenants_data{}.csv".format(current_date),
    )
    return response


@agency_bp.get("/export-owners-data/")
@login_required
def export_owners_csv():
    headers = [
        "ID",
        "Nom & Prénoms",
        "N° Téléphone",
        "Adresse e-mail",
        "N° CNI",
        "Profession",
        "Nombre de propriétés",
        "Date d'ajout",
    ]

    owners = current_user.houseowners.all()

    current_date = datetime.now().strftime("%Y-%m-%d_%H-%M")
    response = Response(
        export_data.generate_owner_csv(owners, headers), mimetype="text/csv"
    )

    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="owners_data_{}.csv".format(current_date),
    )
    return response


@agency_bp.get("/export-houses-data/")
@login_required
def export_houses_csv():
    headers = [
        "ID",
        "Propriétaire",
        "Type de propriété",
        "Loyer",
        "Caution",
        "Nombre de pièces",
        "Situation géographique",
        "Date de mise en location",
        "Disponibilité de la propriété",
        "Date d'ajout",
    ]

    houses = current_user.houses.all()

    current_date = datetime.now().strftime("%Y-%m-%d_%H-%M")
    response = Response(
        export_data.generate_house_csv(houses, headers), mimetype="text/csv"
    )

    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="houses_data_{}.csv".format(current_date),
    )
    return response


@agency_bp.get("/export-payments-data/")
@login_required
def export_payments_csv():
    headers = [
        "ID Transaction",
        "ID Opérateur",
        "Nom & prénom du locataire",
        "Loyer (montant)",
        "Méthode de paiement",
        "Date de paiement",
    ]

    payments = current_user.payments.all()

    current_date = datetime.now().strftime("%Y-%m-%d_%H-%M")
    response = Response(
        export_data.generate_payments_csv(payments, headers), mimetype="text/csv"
    )

    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="payments_data_{}.csv".format(current_date),
    )
    return response

src/dashboard/routes/checkout.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required

checkout_bp = Blueprint("checkout_bp", __name__, url_prefix="/dashboard/")


@checkout_bp.get("/payments/")
@login_required
def checkout():
    page_title = "Liste des paiements de loyers"
    return render_template(
        "checkout/checkout.html", page_title=page_title, current_user=current_user
    )


@checkout_bp.get("/requests/")
@login_required
def transfer_request():
    page_title = "Retraits"
    return render_template(
        "checkout/transfer.html", page_title=page_title, current_user=current_user
    )

src/dashboard/routes/owner.py
import os

from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from flask_login import current_user, login_required

from src.auth.forms.auth_form import ChangePasswordForm
from src.dashboard.forms import OwnerSettingForm
from src.exts import cache, csrf
from src.mixins.decorators import owner_required

owner_bp = Blueprint("owner_bp", __name__, url_prefix="/dashboard/")
csrf.exempt(owner_bp)


@owner_bp.route("/index/", methods=["GET"])
@login_required
@cache.cached(timeout=500)
def dashboard():
    page_title = "Tableau de board"
    return render_template(
        "dashboard/dashboard.html", page_title=page_title, current_user=current_user
    )


@owner_bp.route("/parameters/", methods=["GET", "POST"])
@login_required
@owner_required
def owner_setting():
    page_title = "Paramètres"
    form = OwnerSettingForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        current_user.vn_gender = form.gender.data
        current_user.vn_fullname = form.fullname.data
        current_user.vn_phonenumber_two = form.phonenumber_two.data

        current_user.vn_profession = form.profession.data
        current_user.vn_parent_name = form.parent_name.data

        current_user.vn_device = form.devise.data
        current_user.vn_location = form.location.data
        current_user.vn_birthdate = form.birthdate.data

        current_user.save()
        flash("Votre compte a été mise à jour avec succès.", "success")
        return redirect(url_for("owner_bp.owner_setting"))
    elif request.method == "GET":
        form.gender.data = current_user.vn_gender
        form.fullname.data = current_user.vn_fullname
        form.phonenumber_two.data = current_user.vn_phonenumber_two

        form.profession.data = current_user.vn_profession
        form.parent_name.data = current_user.vn_parent_name

        form.devise.data = current_user.vn_device
        form.location.data = current_user.vn_location
        form.birthdate.data = current_user.vn_birthdate

    return render_template(
        "dashboard/account/owner/settings.html",
        page_title=page_title,
        form=form,
        current_user=current_user,
    )


@owner_bp.route("/change-paswword/", methods=["GET", "POST"])
@login_required
def change_password():
    page_title = "Changer votre mot de passe"
    form = ChangePasswordForm()
    if request.method == "POST" and form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.vn_password = form.new_password.data
            current_user.set_password(form.new_password.data)
            current_user.save()
            flash("Votre mot de passe a été mise à jour avec succès.", "success")
            return redirect(url_for("owner_bp.change_password"))
        else:
            flash("Le mot de passe est invalide.", category="danger")

    return render_template(
        "dashboard/account/password.html",
        page_title=page_title,
        form=form,
        current_user=current_user,
    )


@owner_bp.route("/<filename>/")
@cache.cached(timeout=500)
def avatar(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER_PATH"], filename)


@owner_bp.route("/favicon.png")
@cache.cached(timeout=500)
def favicon():
    return send_from_directory(
        os.path.join(current_app.root_path, "static"), "img/logo/favicon.png"
    )

src/templates/dashboard/account/billing.html
{% extends "dashboard/_base.html" %}

{% block dashboard_content %}
	<div id="billingApp">

		<message-component :show-message-alert="showMessageAlert" :message-alert="messageAlert">
    	</message-component>

    	<div v-if="isLoading" class="preloader">
            <div class="preloader-body">
                <p>Chargement en cours...</p>
                <div class="cssload-container">
                    <div class="cssload-speeding-wheel"></div>
                </div>
            </div>
        </div>

		<div class="row g-2">
			<div class="col-md-4 mb-4">
                <div class="card border-start-lg border-start-primary h-100">
                    <div class="card-body">
                        <div class="d-flex align-items-center">
                            <div class="flex-grow-1">
                                <div class="small fw-bold text-primary mb-2 text-uppercase">solde</div>
                                <div class="h1 fw-700">{ user.total_payments_received } { user.vn_device }</div>
                            </div>
                            <div class="ms-2"><i class="fas fa-dollar-sign fa-2x text-gray-200"></i></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card border-start-lg border-start-primary h-100">
                    <div class="card-body">
                        <div class="d-flex align-items-center">
                            <div class="flex-grow-1">
                                <div class="small fw-bold text-primary mb-2 text-uppercase">Total loyers à collecter</div>
                                <div class="h1 fw-700">{ user.total_house_amount } { user.vn_device }</div>
                            </div>
                            <div class="ms-2"><i class="fas fa-dollar-sign fa-2x text-gray-200"></i></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card border-start-lg border-start-primary h-100">
                    <div class="card-body">
                        <div class="d-flex align-items-center">
                            <div class="flex-grow-1">
                                <div class="small fw-bold text-primary mb-2 text-uppercase">gains sur loyers à collectés</div>
                                <div class="h1 fw-700">{ user.total_house_percent } { user.vn_device }</div>
                            </div>
                            <div class="ms-2"><i class="fas fa-dollar-sign fa-2x text-gray-200"></i></div>
                        </div>
                    </div>
                </div>
            </div>
		</div>

		<div class="row">
			<div class="col-lg-12">
			    <div class="card mb-4">
			    	<div class="card-header">Historique de vos retraits effectués</div>
			    	<div class="card-body px-0">
			    		<div class="d-flex align-items-center justify-content-between px-4">
				    		<div class="d-flex align-items-center">
				    			<i class="fab fa-cc-visa fa-2x cc-color-visa"></i>
				    			<div class="ms-4">
				    				<div class="small">Retrait effectué le 21 Avril 2023 sur le 07070707</div>
				    				<div class="text-xs text-muted">le 04/2024</div>
				    			</div>
				    		</div>
			    		</div>
			    	</div>
			    </div>
		    </div>
	    </div>
    </div>
{% endblock dashboard_content %}

{% block other_js_src %}
    {{ super() }}
    <script type="module" src="{{ url_for('static', filename="js/app/billing.js") }}"></script>
{% endblock other_js_src %}

src/templates/dashboard/account/houses.html
{% extends "dashboard/_base.html" %}

{% block dashboard_content %}
	<div id="othersHousesApp">

		<message-component :show-message-alert="showMessageAlert" :message-alert="messageAlert">
    	</message-component>

    	<div v-if="houses.length == 0" class="card card-body shadow-none bg-transparent border-0">
	        <div class="text-center py-2">
	            <img loading="lazy" class="img-account-profile rounded-circle mb-4" src="{{ url_for('static', filename="img/element/house.svg")}}" alt="">

	            <p class="d-flex justify-content-center text-muted mb-4">
	                Nous n'avons trouvé aucune propriété disponible dans votre région pour le moment.
	            </p>
	        </div>
    	</div>

    	<div v-if="isLoading" class="preloader">
            <div class="preloader-body">
                <p>Chargement en cours...</p>
                <div class="cssload-container">
                    <div class="cssload-speeding-wheel"></div>
                </div>
            </div>
        </div>

		<div v-if="houses.length > 0" class="row">
			<div class="card mb-4">
				<div class="card-header border-bottom bg-transparent">
					<div class="input-group input-group-joined input-group-solid shadow-none">
	                    <input
	                        type="search"
	                        placeholder="Rechercher une propriété ..."
	                        class="form-control shadow-none ps-3"
	                    >
	                    <button type="submit" class="input-group-text"><i class="fas fa-search text-primary fs-6"></i></button>
	                </div>
				</div>

				<div class="card-body">
					<div class="row g-3">
						<template v-for="house in houses" :key="house.house_id">
							<div class="col-md-6 col-xxl-4">
								<div class="card p-2 shadow-sm h-100">
									<div class="card-image-scale rounded-3 position-relative bg-light">
										<img width="100" height="150" loading="lazy" class="card-img" src="/static/img/element/house.svg" alt="card-image">
										<div class="card-img-overlay d-flex flex-column p-2 z-index-1">
											<img height="50" width="50" loading="lazy" class="rounded-2" src="/static/img/logo/favicon.png" alt="venone-logo">
									    </div>
									</div>
									<div class="card-body px-2">
										<p class="mb-2 mb-sm-0">
											<span class="badge bg-blue-soft text-blue p-2 fw-700 rounded-1 text-uppercase">{ house.house_type }</span>
											<span v-if="house.house_closed" class="ms-2 badge bg-red-soft text-red p-2 fw-700 rounded-1 text-uppercase">
												indisponible
											</span>
										</p>
										<p class="mb-2">
											<h2 class="h1 fw-700">
												<i class="fas fa-dollar-sign text-primary me-1"></i>
												{ house.house_rent } { house.house_devise }
											</h2>
										</p>
										<p class="mb-2">
											<span class="h4">
												<i class="fas fa-map-marker-alt me-2 text-primary"></i>
												{ house.house_address }
											</span>
										</p>
										<p class="mb-2">
											<h2 class="h4 fw-600"><u>Conditions</u>: </h2>
											<ul class="list-group mb-4">
												<li class="list-group-item fw-light d-flex">
													<i class="fas fa-check-circle text-success me-2"></i>
													<span>{ house.house_month } mois loyer</span>
												</li>
												<li class="list-group-item fw-light d-flex mb-0">
													<i class="fas fa-check-circle text-success me-2"></i>
													<span>{ house.house_number_room } pièces</span>
												</li>
												<li class="list-group-item fw-light d-flex mb-0">
													<i class="fas fa-check-circle text-success me-2"></i>
													<span>{ house.house_guaranty } { house.house_devise } caution</span>
												</li>
											</ul>
										</p>
										<div class="mb-0">
											<a rel="nofollow"
												target="_blank"
												href="https://wa.me/+2250747473627?text=Puis-je avoir plus d'information sur cette proprété ?"
												class="btn btn-success"
											>Contacter l'agence</a>
										</div>
									</div>
								</div>
							</div>
						</template>
					</div>

					<paginate-component
						:current-page="currentPage"
						:total-pages="totalPages"
						:next-page="nextPage"
						:prev-page="prevPage"
					></paginate-component>
				</div>
			</div>
	    </div>
    </div>
{% endblock dashboard_content %}

{% block other_js_src %}
    {{ super() }}
    <script type="module" src="{{ url_for('static', filename="js/app/hscheck.js") }}"></script>
{% endblock other_js_src %}

src/templates/dashboard/account/password.html
{% extends "dashboard/account/owner/settings.html" %}

{% block settings_content %}
    <div class="col-lg-8">
	    <div class="card mb-4">
	    	<div class="card-header">Changeer de mot de passe</div>
	    	<div class="card-body">
			    <form action="{{ url_for('owner_bp.change_password') }}" method="POST">
			    	{% for field in form %}
			    		<div class="mb-3">
				    		{{ field.label(class="small mb-1") }}
						    {% if field.errors %}
								{{ field(class="form-control is-invalid") }}
								<div class="invalid-feedback">
									{% for error in field.errors %}
									<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% else %}
								{{ field(class="form-control") }}
							{% endif %}
				    	</div>
			    	{% endfor %}

			    	<div class="d-grid">
				    	<button type="submit" class="btn btn-primary mb-0">Mettre à jour votre mot de passe </button>
				    </div>
			    </form>
	    	</div>
	    </div>
    </div>

    <div class="col-lg-4">
    	<div class="card mb-4">
    		<div class="card-header text-danger">Supprimer votre compte</div>
    		<div class="card-body">
    			<p>
    				La suppression de votre compte est une action permanente et ne peut être annulée. Si vous êtes sûr de vouloir supprimer votre compte, sélectionnez le bouton ci-dessous.
    			</p>
    			<form action="{{ url_for('agency_bp.delete_account') }}" method="POST">
    				<div class="d-grid">
	    				<button class="btn btn-danger-soft fw-bold text-danger text-uppercase" type="submit">
	    					<span class="nav-link-icon me-2">
	                        	<i data-feather="trash"></i>
	                    	</span>
	    					Je comprends, supprimer mon compte
	    				</button>
    				</div>
				</form>
    		</div>
    	</div>
    </div>
{% endblock settings_content %}